---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-test-service
  #annotations: service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:217243425880:certificate/12a8e2b8-9885-4f2a-a006-8da9cea4bc7e
spec:
  selector:
    app: docker-k8s-test
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8085
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30010
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-test-deploy
spec:
  selector:
    matchLabels:
      app: docker-k8s-test
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-k8s-test
    spec:
      containers:
        - name: docker-k8s-test
          image: shlomigonen/docker_k8s_test_container:BUILD_VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8080